skills:
  hero:
    rapid_strike:
      name: Rapid Strike
      chance: 10
      value: 2
      action: attack
      class_name: RapidStrike

    magic_shield:
      name: Magic Shield
      chance: 20
      value: 2
      action: defence
      class_name: MagicShield
